# cd ./docker-template/codebook_env && set -a && source .env && docker-compose -f dist/debian/docker-compose-codebook_env.yaml build
services:
  codebook_env:
    build:
      # only necessary if rebuilding image
      context: .
      dockerfile: codebook.Dockerfile
      args:
        - JHUB_VER
        - PY_VER
        - DEPLOY_KEY
        - REPO_OWNER
        - REPO_NAME
    image: registry.vathes.com/sciops/codebook_${REPO_NAME}:singleuser-${JHUB_VER}-py${PY_VER}-${WORKFLOW_VERSION}