name: codebook-profile-build
on:
  workflow_call:
    inputs:
      jhub_ver:
        required: true
        type: string
      py_ver:
        required: true
        type: string
      workflow_version:
        required: true
        type: string
    secrets:
      RUNNER_PAT:
        required: true
      RUNNER_AWS_ACCESS_KEY_ID:
        required: true
      RUNNER_AWS_SECRET_ACCESS_KEY:
        required: true
      DEPLOY_SSH_KEY_BASE64:
        required: true
      DOCKER_REGISTRY_HOST:
        required: true
      DOCKER_REGISTRY_REPO:
        required: true
      DOCKER_REGISTRY_USERNAME:
        required: true
      DOCKER_REGISTRY_PASSWORD:
        required: true
jobs:
  start-runner:
    timeout-minutes: 5              # normally it only takes 1-2 minutes
    name: Start self-hosted EC2 runner   
    runs-on: ubuntu-latest
    permissions:
      actions: write        
    steps:      
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: NextChapterSoftware/ec2-action-builder@v1
        with:
          github_token: ${{ secrets.RUNNER_PAT}}
          aws_access_key_id: ${{ secrets.RUNNER_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.RUNNER_AWS_SECRET_ACCESS_KEY }}
          aws_region: "us-east-2"
          ec2_instance_type: t3a.medium
          ec2_ami_id: ami-0adf61e89c60d1313
          ec2_subnet_id: "subnet-0a602071414b8b2eb"
          ec2_security_group_id: "sg-02810c38b0dcb2462"
          ec2_instance_ttl: 60                # Optional (default is 60 minutes)
          ec2_spot_instance_strategy: BestEffort    # Other options are: SpotOnly, BestEffort, MaxPerformance 
  ## Build/Publish codebook env image
  build_codebook_image:
    needs:
      - start-runner
    runs-on: ${{ github.run_id }}  
    env:
      JHUB_VER: ${{inputs.jhub_ver}}
      PY_VER: ${{inputs.py_ver}}
      WORKFLOW_VERSION: ${{inputs.workflow_version}}
    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v4
        with:
          path: 'main'
      - name: Checkout cicd repo that has common docker template
        uses: actions/checkout@v4
        with:
          repository: 'dj-sciops/.github'
          # repository: 'yambottle/dj-sciops.github'
          path: 'cicd'
      - id: build_env
        name: Build codebook env image
        run: |
          ## Get docker template
          cp -r ${GITHUB_WORKSPACE}/cicd/.github/docker-template/codebook-profile ./main/docker/

          ## Get build info
          cd ${GITHUB_WORKSPACE}/main/docker/codebook-profile
          export REPO_NAME=${{github.event.repository.name}}
          export REPO_OWNER=${{github.repository_owner}}

          echo "${{secrets.DEPLOY_SSH_KEY_BASE64}}" | base64 -di >> ${REPO_NAME}-deploy.pem
          chmod u=r,g-rwx,o-rwx ${REPO_NAME}-deploy.pem
          export DEPLOY_KEY=${REPO_NAME}-deploy.pem

          ## Build image
          docker compose build
      - name: Login to vathes Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_HOST }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Push codebook image
        run: |
          export IMAGE=${{ secrets.DOCKER_REGISTRY_HOST }}/${{ secrets.DOCKER_REGISTRY_REPO }}/codebook_${{github.event.repository.name}}
          export TAG=singleuser-${{env.JHUB_VER}}-py${{env.PY_VER}}-${{env.WORKFLOW_VERSION}}
          echo ${IMAGE} ${TAG}
          docker push "${IMAGE}:${TAG}"
          echo ${IMAGE} latest
          docker tag "${IMAGE}:${TAG}" "${IMAGE}:latest"
          docker push "${IMAGE}:latest"